config/routes.rb
Rails.application.routes.draw do
  root to: "games#index", as: "root"
  
  resources :players, only: [:index, :show]
  
  resources :teams, only: [:index, :show]
  
  resources :games, only: [:index, :show]
  
  get "search", to: "players#search", as: "search"
  
  get "daily_projections", to: "players#daily_projections", as: "daily_projections"
  
  get "daily_starting_lineups", to: "players#daily_starting_lineups", as: "daily_starting_lineups"
  
  get "entire_day_games/:date", to: "games#entire_day_games", as: "entire_day_games"
  
  get "todays_odds", to: "games#todays_odds", as: "todays_odds"
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :date, :home_team_id, :away_team_id, presence: true

  scope :previous_games, -> { where("date < ?", Date.current).order(:date) }
  scope :todays_games, -> { where(date: Date.parse(Time.now.to_s) ) }

  has_many(
    :player_games,
    class_name: "PlayerGame",
    foreign_key: :game_id,
    primary_key: :id
  )

  belongs_to(
    :home_team,
    class_name: "Team",
    foreign_key: :home_team_id,
    primary_key: :id
  )

  belongs_to(
    :away_team,
    class_name: "Team",
    foreign_key: :away_team_id,
    primary_key: :id
  )


  has_many :players, through: :player_games, source: :player
  
  def teams
    [self.home_team, self.away_team]
  end
  
  def self.get_todays_odds
    game_array = []
    
    page = Nokogiri::HTML(open("http://www.oddsshark.com/nba/odds"))
    rows = page.css(".odds-page-container")
    rows.each do |row|
      date = row.css(".header-time").text
      
      game_hash = Hash.new { |h,k| h[k] = Hash.new }
      line_break = row.css(".first.teams a").at_css("br")
      line_break.content = ","
      teams = row.css(".first.teams a").text.split(",")
      
      game_hash["date"] = date
      game_hash["first_team"]["name"] = teams[0].downcase!
      game_hash["second_team"]["name"] = teams[1].downcase!
      
      #5 ==> BetOnline
      #4 ==> MyBookie.Ag
      #3 ==> Bovada
      #2 ==> 5Dimes
      [5, 4, 3, 2].each do |num|
        unless row.css(".book.total.book-#{num} span.total").text.empty?
          total = row.css(".book.total.book-#{num} span.total").text
          spreads = row.css(".book.spread.book-#{num} span.spread")
          
          game_hash["total"] = total
          game_hash["first_team"]["spread"] = spreads[0].text
          game_hash["second_team"]["spread"] = spreads[1].text
          
          break
        else
          next
        end
      end
      
      game_array << game_hash
    end
    
    game_array
  end

  def create_player_games
    if self.player_games.empty?
      current_home_team = self.home_team
      current_away_team = self.away_team

      current_teams = [current_home_team, current_away_team]

      domain = "http://www.basketball-reference.com"
      path = "boxscores"
      game_detail = "#{ self.date.strftime('%Y%m%d') }0#{ current_home_team.name }"
      page = Nokogiri::HTML(open("#{ domain }/#{ path }/#{ game_detail }.html"))

      current_teams.each do |team|
        table = page.css("#div_#{ team.name }_basic tr")
        table.each_with_index do |row, index|
          name = row.css("a").text

          next if name.empty?
          next if row.css("td")[2].nil?
          
          minutes_array = row.css("td")[1].text.split(":")
          minutes = (minutes_array[0].to_i + minutes_array[1].to_i/60.0).round(2)
          
          fgm = row.css("td")[2].text.to_i
          fga = row.css("td")[3].text.to_i
          three_fgm = row.css("td")[5].text.to_i
          three_fga = row.css("td")[6].text.to_i
          ftm = row.css("td")[8].text.to_i
          fta = row.css("td")[9].text.to_i
          rebounds = row.css("td")[13].text.to_i
          assists = row.css("td")[14].text.to_i
          steals = row.css("td")[15].text.to_i
          blocks = row.css("td")[16].text.to_i
          turnovers = row.css("td")[17].text.to_i
          points = row.css("td")[19].text.to_i

          current_player = Player.find_by_name(name) || Player.create({ name: name, position: "NA", team_id: team.id})
          
          unless current_player.team_id == team.id
            current_player.update(team_id: team.id)
          end

          PlayerGame.create(
            player_id: current_player.id,
            game_id: self.id,
            team_id: team.id,
            points: points,
            rebounds: rebounds,
            assists: assists,
            steals: steals,
            blocks: blocks,
            turnovers: turnovers,
            minutes: minutes,
            fga: fga,
            fgm: fgm,
            three_fga: three_fga,
            three_fgm: three_fgm,
            fta: fta,
            ftm: ftm,
          )
        end
      end
    end
  end
  
  def other_team(this_team)
    if self.home_team == this_team
      return self.away_team
    elsif self.away_team == this_team
      return self.home_team
    else
      return nil
    end
  end
  
  def total_fantasy_points_for_team(team_id)
    Team.find(team_id).get_fantasy_point_for_game(self.id)
  end
  
  
end

app/controllers/games_controller.rb
require 'nokogiri'
require 'open-uri'

class GamesController < ApplicationController
  before_action :load_new_data, only: [:index]
  
  def index
    render :index
  end
  
  def show
    @game = Game.eager_load(:home_team, :away_team, player_games: [:team, :player]).find(params[:id])
    @home_team_players = []
    @away_team_players = []
    
    @game.player_games.each do |player_game|
      if player_game.team_id == @game.home_team_id
        @home_team_players << player_game
      elsif player_game.team_id == @game.away_team_id
        @away_team_players << player_game
      end
    end
        
    if @game
      render :show
    else
      render json: "Game does not exist"
    end
  end
  
  def entire_day_games
    @date = params[:date]
    @entire_day_games = Game.eager_load(:home_team, :away_team, player_games: [player: [:team ]]).where(date: params[:date])
        
    @entire_day_player_games = []
    
    @entire_day_games.each do |game|
      @entire_day_player_games.concat(game.player_games)
    end
    
    @entire_day_player_games.sort! { |x, y| y.total_fantasy_points <=> x.total_fantasy_points }
    render :entire_day_games
  end
  
  def todays_odds
    @game_array = Game.get_todays_odds
    
    render :todays_odds
  end
  
  private
  
  def load_new_data
    @previous_games = Game.eager_load(:home_team, :away_team, player_games: [player: [ :team ]]).previous_games
  
    @previous_games.each do |game|
      game.create_player_games if game.player_games.empty?
    end
  end
    
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/entire_day_games.html.erb
<h2>For <%= Date.parse(@date).strftime("%a, %b %d, %Y") %></h2>
<br>

<ul class="group">
  <li class="table-name">Name</li>
  <li class="table-attribute">Position</li>
  <li class="table-attribute">Team</li>
  <li class="table-attribute">Opponent</li>
  <li class="table-attribute">Total Fantasy Points</li>
  <li class="table-attribute">Minutes Played</li>
  <li class="table-attribute">Points Per Minute</li>
</ul>

<% @entire_day_player_games.each do |player_game| %>
  <%  total_fantasy_points = player_game.total_fantasy_points %>
  <ul class="group">
    <li class="table-name"><a href="<%= player_url(player_game.player) %>"><%= player_game.player.name %></a></li>
    <li class="table-attribute"><%= player_game.player.position %></li>
    <li class="table-attribute"><a href="<%= team_url(player_game.team) %>"><%= player_game.team.name %></a></li>
    <li class="table-attribute"><a href="<%= team_url(player_game.game.other_team(player_game.team)) %>"><%= player_game.game.other_team(player_game.team).name %></a></li>
    <li class="table-attribute"><%= total_fantasy_points %></li>
    <li class="table-attribute"><%= player_game.minutes %></li>
    <li class="table-attribute"><%= total_fantasy_points/player_game.minutes %></li>
  </ul>
<% end %>

app/views/games/index.html.erb
<% dates_hash = {} %>
<% @previous_games.reverse.each do |game| %>
  <% if dates_hash[ game.date.strftime("%d-%b-%Y") ].nil?  %>
    <br>
    <a href="<%=  entire_day_games_url(game.date.strftime("%d-%b-%Y")) %>"><%= game.date.strftime("%d-%b-%Y") %></a>
  <% end %>
  
  <% dates_hash[ game.date.strftime("%d-%b-%Y") ] ||= true %>
  <p><a href="<%= game_url(game) %>"><%=  game.date %> - <%= game.away_team.name %> at <%= game.home_team.name %></a></p>
<% end %>

app/views/games/show.html.erb
<h2><a href="<%= team_url(@game.home_team) %>"><%= @game.home_team.name %></a></h2>
<ul class="group">
  <li class="table-name">Name</li>
  <li class="table-attribute">Position</li>
  <% @game.player_games[0].attributes.each do |key, value| %>
    <% next if key == "id" || key == "created_at" || key == "updated_at" || key == "player_id" || key == "game_id" || key == "team_id" || key == "fga" || key == "three_fga" || key == "fta" %>
    <li class="table-attribute"><%= key %></li>
  <% end %>
  <li class="table-attribute">Total Fantasy Points</li>
  <li class="table-attribute">Percentage of Team Points</li>
</ul>
<% @home_team_players.each do |player_game| %>
  <ul class="group">
    <li class="table-name"><a href="<%= player_url(player_game.player_id) %>"><%= player_game.player.name %></a></li>
    <li class="table-attribute"><%= player_game.player.position %></li>
    <% player_game.attributes.each do |key, value| %>
      <% next if key == "id" || key == "created_at" || key == "updated_at" || key == "player_id" || key == "game_id" || key == "team_id" || key == "fga" || key == "three_fga" || key == "fta"%>
      <li class="table-attribute"><%= value %></li>
    <% end %>
    <li class="table-attribute"><%= player_game.total_fantasy_points %></li>
    <li class="table-attribute"><%= (player_game.total_fantasy_points/@game.total_fantasy_points_for_team(@game.home_team)).round(2) %></li>
  </ul>
<% end %>

<br>
<h2><a href="<%= team_url(@game.away_team) %>"><%= @game.away_team.name %></a></h2>
<ul class="group">
  <li class="table-name">Name</li>
  <li class="table-attribute">Position</li>
  <% @game.player_games[0].attributes.each do |key, value| %>
    <% next if key == "id" || key == "created_at" || key == "updated_at" || key == "player_id" || key == "game_id" || key == "team_id" || key == "fga" || key == "three_fga" || key == "fta"%>
    <li class="table-attribute"><%= key %></li>
  <% end %>
  <li class="table-attribute">Total Fantasy Points</li>
  <li class="table-attribute">Percentage of Team Points</li>
</ul>
<% @away_team_players.each do |player_game| %>
  <ul class="group">
    <li class="table-name"><a href="<%= player_url(player_game.player_id) %>"><%= player_game.player.name %></a></li>
    <li class="table-attribute"><%= player_game.player.position %></li>
    <% player_game.attributes.each do |key, value| %>
      <% next if key == "id" || key == "created_at" || key == "updated_at" || key == "player_id" || key == "game_id" || key == "team_id" || key == "fga" || key == "three_fga" || key == "fta"%>
      <li class="table-attribute"> <%= value %></li>
    <% end %>
    <li class="table-attribute"><%= player_game.total_fantasy_points %></li>
    <li class="table-attribute"><%= (player_game.total_fantasy_points/@game.total_fantasy_points_for_team(@game.away_team)).round(2) %></li>
  </ul>
<% end %>

app/views/games/todays_odds.html.erb
<h2>Today's Odds</h2>
<ul class="group">
  <li class="table-name">Date</li>
  <li class="table-name">Away Team</li>
  <li class="table-name">Home Team</li>
  <li class="table-attribute">Total</li>
  <li class="table-attribute">Away Team Spread</li>
  <li class="table-attribute">Home Team Spread</li>
</ul>
<% @game_array.each do |game| %>
  <ul class="group">
    <li class="table-name"><%= game["date"] %></li>
    <li class="table-name"><%= game["first_team"]["name"] %></li>
    <li class="table-name"><%= game["second_team"]["name"] %></li>
    <li class="table-attribute"><%= game["total"] %></li>
    <li class="table-attribute"><%= game["first_team"]["spread"] %></li>
    <li class="table-attribute"><%= game["second_team"]["spread"] %></li>
  </ul>
<% end %>