config/routes.rb
Rails.application.routes.draw do
  root to: "games#index", as: "root"
  
  resources :players, only: [:index, :show]
  
  resources :teams, only: [:index, :show]
  
  resources :games, only: [:index, :show]
  
  get "search", to: "players#search", as: "search"
  
  get "daily_projections", to: "players#daily_projections", as: "daily_projections"
  
  get "daily_starting_lineups", to: "players#daily_starting_lineups", as: "daily_starting_lineups"
  
  get "entire_day_games/:date", to: "games#entire_day_games", as: "entire_day_games"
  
  get "todays_odds", to: "games#todays_odds", as: "todays_odds"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DFSApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <ul class="group">
    <li class="header-link"><a href="<%= root_url %>">Games Index</a></li>
    <li class="header-link"><a href="<%= teams_url %>">Teams index</a></li>
    <li class="header-link"><a href="<%= daily_projections_url %>">Daily Projections</a></li>
    <li class="header-link"><a href="<%= daily_starting_lineups_url %>">Starting Lineups</a></li>
    <li class="header-link"><a href="<%= todays_odds_url %>">Today's Odds</a></li>
    <form action="<%= search_url %>" method="GET">
      <%= auth_token %>
      <input list="matches" name="player[name]" placeholder="Search Player">
        <li class="header-link">
          <datalist id="matches">
            <% Player.eager_load(:team).select(:name, :team_id).each do |player| %>
              <option value="<%= player.name %>"><%= Team.find(player.team_id).name %></option>
            <% end %>
          </datalist>
        </li>
      </input>
    </form>
  </ul>
</header>
<%= yield %>

</body>
</html>